import { Box } from './types';

/**
 * First-launch sample inventory, carried over from the original Garage Boxes
 * tab (data/garage-boxes.json). Photos are not seeded — those lived on the
 * website's server; in the standalone app you add your own from the camera or
 * photo library. Users can wipe this and start fresh from Settings.
 */
export const SEED_BOXES: Box[] = [
  {
    id: 'box7',
    number: 1,
    label: 'Extension Cords',
    note: '',
    photos: [],
    items: [
      'Yellow extension cord (heavy gauge)',
      'Orange extension cords - regular and extra long (2)',
      'Thin Green extension cords (3)',
      'White extension cords (4)',
      'Black storage bin',
    ],
  },
  {
    id: 'box2',
    number: 2,
    label: 'Paint Supplies',
    note: '',
    photos: [],
    items: [
      'Anvil sheetrock mud finishing trowel',
      '3M sandpaper assortment (multiple grits, 180/220)',
      'Purple 3M sanding sheets',
      'Steel wool',
      'Canvas drop cloth',
      'White fabric / liner',
      'Paint rollers',
      'Paint roller pans',
    ],
  },
  {
    id: 'box3',
    number: 3,
    label: 'Sports & Work Gear',
    note: '',
    photos: [],
    items: [
      '2x - Pickleball paddles',
      '2x - Tennis rackets',
      'Everbilt brown heavy-duty tarp 8 ft',
      'DeWalt work boots (brown)',
      'Baseball glove',
    ],
  },
  {
    id: 'box4',
    number: 4,
    label: 'Hunting Gear',
    note: '',
    photos: [],
    items: [
      'Burlap blind material / camo netting',
      'Camo shirt and pants',
      'Tripod seat for hunting',
      "Hunter's Specialties game cleaning gloves",
      'Scent Killer anti-perspirant & deodorant',
      'Orange flagging tape',
      'Camo gloves',
      'Yellow rain poncho / disposable',
    ],
  },
  {
    id: 'box5',
    number: 5,
    label: 'Bags & Coolers',
    note: '',
    photos: [],
    items: [
      'Maroon duffel bag',
      'Camo hunting backpack',
      '2x - LSU soft cooler bag (purple, large)',
      '1x - LSU soft cooler bag (purple, small)',
    ],
  },
  {
    id: 'box6',
    number: 6,
    label: 'Christmas Décor',
    note: '',
    photos: [],
    items: [
      'Tiffany & Co. Christmas Tree Topper',
      '2x White & gold nutcracker (pair)',
      'Flocked pine swag with red berries & pinecone',
    ],
  },
  {
    id: 'box_1783462300213',
    number: 7,
    label: 'Christmas & Holiday',
    note: '',
    photos: [],
    items: ['4th of July Bunting', '2x Clear storage containers behind with xmas stuff'],
  },
  {
    id: 'box_1783462379723',
    number: 8,
    label: 'Electrical Stuff',
    note: '',
    photos: [],
    items: [
      'DC to AC Inverter',
      'Surge protectors (several)',
      'Amp for speakers',
      '3 prong plugs (6)',
      '3 way smart plug',
      '12v battery charger',
      'Trickle charger',
    ],
  },
  {
    id: 'box_1783469628594',
    number: 9,
    label: 'Small Electronics',
    note: '',
    photos: [],
    items: [
      'Remote control',
      'Fire TV remote',
      'Smart plugs',
      'LED light bulb',
      'USB charger',
      'Power adapter',
      'Wireless mouse',
      'Bluetooth speaker',
      'Headphones',
      'AC adapter',
      'Cables',
      'Smart home hub',
    ],
  },
  {
    id: 'box_1783469703141',
    number: 10,
    label: 'Metal Brackets & Rope',
    note: '',
    photos: [],
    items: [
      'Storage accessory hooks boxes',
      'White metal mounting brackets',
      'Yellow fiberglass measuring tape',
      'Coiled rope',
      'White rack steel angles',
    ],
  },
];
